apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:iStDSVnfElz2/S5rYqaREQWUHJc9xT3u6awyM26lrF19xXFkQKJing==,iv:dzGAJcjhMkvaEMtfgZU8FtJpZz0AgOh82NE8ui3IJ4g=,tag:VfosFkpg9g1f2CpEa9Kbsg==,type:str]
sops:
  age:
    - recipient: age1n2jr2xgfk7ak8wwpn538vpc4t37aqrlmwv0hy2g30tv33j26c42slhm8q7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZytsL242aGZ1UlNEdnBu
        ckQ0aHo2ZEszZlNnUVlYT0FqSmlMbjI3N1N3CklieUJ6SmE0R2RNRlNHM3Z6TXJW
        cnd4c3d6QmFwdFA4dGo2SUtNK2JlNEEKLS0tIG04STdTSXJBYUR4dHROVXdTK216
        NFgyUWJFOWtYYUpRbndnR2tBeUpCZTQK0sVeQku5oK3FHGvsEhaQPngQ6pXeP+Pw
        JpeZ6cCJPT8cUXmI70+8Z6TJrI2zo9wKJcnaJRTSDmf7UCLq815nQw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T10:59:50Z"
  mac: ENC[AES256_GCM,data:akPvM1bKZRK0fxkI0suQ9kmzsF3dipKXys7DF24yIjl69cegSXd1f+wGZ4OeMeDtb5KDGsFITa/d0g2Zid+QVdX91JmfR7+fM1PHytS7sBnSYdDMIbzJnjoQugwS4oyjlGbryqkTj4mRedb9e08QNQKEtUS8/AAgATLzZEzWPPg=,iv:iAmDtLgMFSyZpmJ9vYI5s8AaGS7ncBRS95KNafGdim0=,tag:SUN1nG6woZZmyPK8yIVNXQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
