apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:CWW4ffIVUmci,iv:fZIz4TkWnpWrMUMsmWCCFLloBIgrak4VkrC/yw8vnSY=,tag:yvk83Q1gm+Pi+JDrlviKMA==,type:str]
sops:
  age:
    - recipient: age1n2jr2xgfk7ak8wwpn538vpc4t37aqrlmwv0hy2g30tv33j26c42slhm8q7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWckJOWWtObWRjUXR5RVFL
        cWEwSWw1MFZMeVg1MHFkcm1NUDZVNEJjYXpvCjBtMTlNcXlnVVl3OU1UYjQ0MHIv
        NEs1THI2ZllncWJjK0toUFlJekloakkKLS0tIHlOOCtLNlZ5OCsxUnNudkgrMCtk
        ME1UV2VpSXUrYkw2UFFWQm1XaUE1V0kKbZfnHkE3g0m1jHOu45M3JocuuVic7578
        Gv1TTHCBPBaA4Rw4x9Qfq4Pn+qK6YLAL3PG8D3wy8arl9AgjQ0gtCA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T10:59:50Z"
  mac: ENC[AES256_GCM,data:EtfabCKxb1lLFjjN+zB4/xxiGwkOgCNvVDic8G9+W3ktRK7BkhDV11OGZwBTWrnyd6tt64Y132ihqKP/rW141ThXGW0nLO+hzeBMpu88c3FQuYWbsU4AnEx3P3DXuAr1bdK0DzgG/dHQTtT6FOQfimiSPtnEG7AStjPiGkjbkSw=,iv:T65hBq74vjcMW4dVXUFLvq5WudV9UoI21pgEGsslYjg=,tag:tHNJbFVON52jJnR5QJYxmA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
