apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:UEe6ISdXSPgrMn6B8Wos5rmGnLBjrktISXBxqYgk1gQ=,iv:tYWU0w3Vt0WyIoNHyWtyOiyGT1SaWzXmPBtQHCZQkX8=,tag:ieqT9EBKBycaCdvPWMi3nQ==,type:str]
sops:
  age:
    - recipient: age1n2jr2xgfk7ak8wwpn538vpc4t37aqrlmwv0hy2g30tv33j26c42slhm8q7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQTJZN2U4WTFPZDdJMmVi
        eURTSVNtOGNOaXEwWjlWRGVMdG04Z3JXdXg0ClNYRXp6S25uT3lnZGVwaDV4ejE0
        NXBzRVlHTnp0dVlsbTRPS2hCYkN3R3MKLS0tIHR1SENXdjVuY0FEdGhoRnY1SW5E
        MmxYNjdLQ0l3SDJqdHdwZG9RK00ra2cKPIn2/KcbhKODDs8/bQBLn2dPDSUcYBSd
        up/TptH0sPcNlVEuDXhIkG04mj6fxix5GVpSf/k30kI5heP/O1nmcQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T10:59:50Z"
  mac: ENC[AES256_GCM,data:QaEpxhGues2FHF41PSDvFzqQI68Xts8VKrShIK7Q0gE9K0rQvvqNFocXGb9Iad54uw+p1Wzrta5abzbxdTI54hn1Dl811xeWXg818v3PGei60ksHmUY4luS9EqElC1l+M0+dEksiskzDkvoYLn+DtbvKa28bWp3JszCnpQfQY1Q=,iv:dQjL9vdJ3YsiOq0o6c/nocrbG1jJRUuJNhsl3URiNjY=,tag:3lzlid4L85o/3nANV+UJcg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
