apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:kGuT1fL1IJBp41rw+S3gxn5PjYmhP9yTIUDDgYWeoyzkgP1r8OC2urCwblXL6HbtESc4bV7prlQ2E5tB+pGOD4CVBeYUe0A9SXgB820455scpQ8+ChLQjXPeC+tViGqt6Bm/2luV+/VxJi6fqjvW5J8mthXZurzPVlrIRFYC3pFwLB8G3eZByaX0vnbVtNXkk5Xg3uraaMCCvSLWL90PSoD/e4CLsn4arVA21RlOXRwIlNyO,iv:Yg7u/a0ZNW1tjBx3E1YtfwGeo/ptoOkI8eFQsj4HUqU=,tag:njcD7C6GnUfPeDb5tAmegQ==,type:str]
sops:
  age:
    - recipient: age1n2jr2xgfk7ak8wwpn538vpc4t37aqrlmwv0hy2g30tv33j26c42slhm8q7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQ3BFZW5nd3dQaHdRWHAv
        WEtpcEh0SGVOazhTbVYzWVIyZ1FUTEo3VlNnCmFpQ1F6WmtSWGpVRGx3SHpBMUNl
        a2JrL3JIUkJSZkNKb3ZSd3pKS0ZuNU0KLS0tIDQ5TDFVQ1hKQmxTeHFESFVmQ3Va
        YkFKN1lNWlYxNDlyaXdjbFFQKzJZeGMKYFA6ucidtphxKSAgwT65LQsh5Yo3oY7e
        WhGskS+WyP7W4WSCNDG/LDc46hyMwJTSkxSsw2v2/d6VRLId1c0YWA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T10:59:50Z"
  mac: ENC[AES256_GCM,data:q1ZEouWKdAOo9aNu5uaw2eGoxL7Z/mTpeJ30nfpzW3Ysxs6Ir0AyS/bzFk7tT83EYymSP4JhWwroUccLeRkA6hsILYuW6/GQc3SZEDZiiQX/frvZy00ImB1K6NaCSC4nyurAXjZRkohNQftb8LHZBiZUE5nw2zb82+iIfkjyMhE=,iv:NFrr7Dez7TcMVkKWxnFbiiXJgKNVlZFE1h6jzTxZH98=,tag:DPMMmrM/O/QwamHjj6sJOg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
