apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:je1eQBpMZh6YMBHaLxpa0z/rxeGyiSVe421pLctnqqUiU6urzIdPFA==,iv:hk687EHCULkjkz3rqzcl16Ky6XL6xj7r6W8NRevPP78=,tag:qJHRfcuI4HgdoTK53yny5g==,type:str]
sops:
  age:
    - recipient: age1n2jr2xgfk7ak8wwpn538vpc4t37aqrlmwv0hy2g30tv33j26c42slhm8q7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETnp4SmJJNVhEMENoZVFK
        U2tRQ3NkaFJRSTNEQnZrL0R0U1ZybTJCemd3CkkzNDB6dy9QN3hLb0wzdmVzRjIz
        QmI4SklPTnl1WlBpenozYnZuK3BLZzgKLS0tIEFpSWNNd3Q1bFRvdmRaazJobytz
        RmdCT0FVRjgvWmR1Wm1mbElFekM1N1kKovye52ObVRiZ4Ob+/p2+dOBLC12psB85
        O910YDhqbS+qyQMcQQ9zMxl/83PFC++LCGOCjr8ntunusjraNynKRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T10:59:50Z"
  mac: ENC[AES256_GCM,data:yI8vSBEgnwPNJG+Nc1l/hGcdz3nmBAOAmzSHwjSBVpxRPWptVeAdqQI770LQU98m3jI3CytVYcS/m9qS7lyVInPTkr2tyCrK4BioCeNUvA/LRQvy4Dx/479dKkcAVHhQiPjGivx/KJx2ZELJg/3TT0k12HRWketJ3hnnereWIOc=,iv:hlFFvYI9pH3FC/SyeYyXCxwa+tlcYVmS2MBxdvkouTM=,tag:Sm+kZnh9hxoDTYidJYUCTg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
